# Generated by Django 2.2 on 2020-08-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeshack', '0002_auto_20200811_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memes',
            old_name='text',
            new_name='comment',
        ),
    ]
